package com.autumnwind.botb.util;

import com.autumnwind.botb.BloodOnTheBlocktower;
import java.util.List;
import net.minecraft.locale.Language;

public class Jinxes {

    public record JinxInfo(Role role1, Role role2) {
        public String description() {
            return Language.getInstance().getOrDefault("jinx." + BloodOnTheBlocktower.MOD_ID + "." + role1.getId() + "." + role2.getId());
        }
    }

    public static final List<JinxInfo> JINX_LIST = List.of(
            new JinxInfo(Role.ALCHEMIST, Role.BOFFIN),
            new JinxInfo(Role.ALCHEMIST, Role.MARIONETTE),
            new JinxInfo(Role.ALCHEMIST, Role.MASTERMIND),
            new JinxInfo(Role.ALCHEMIST, Role.ORGAN_GRINDER),
            new JinxInfo(Role.ALCHEMIST, Role.SPY),
            new JinxInfo(Role.ALCHEMIST, Role.SUMMONER),
            new JinxInfo(Role.ALCHEMIST, Role.WIDOW),
            new JinxInfo(Role.ALCHEMIST, Role.WRAITH),
            new JinxInfo(Role.AL_HADIKHIA, Role.MASTERMIND),
            new JinxInfo(Role.AL_HADIKHIA, Role.PRINCESS),
            new JinxInfo(Role.BOFFIN, Role.CULT_LEADER),
            new JinxInfo(Role.BOFFIN, Role.DRUNK),
            new JinxInfo(Role.BOFFIN, Role.GOON),
            new JinxInfo(Role.BOFFIN, Role.HERETIC),
            new JinxInfo(Role.BOFFIN, Role.OGRE),
            new JinxInfo(Role.BOFFIN, Role.POLITICIAN),
            new JinxInfo(Role.BOFFIN, Role.VILLAGE_IDIOT),
            new JinxInfo(Role.BOUNTY_HUNTER, Role.KAZALI),
            new JinxInfo(Role.BOUNTY_HUNTER, Role.PHILOSOPHER),
            new JinxInfo(Role.BUTLER, Role.ORGAN_GRINDER),
            new JinxInfo(Role.CANNIBAL, Role.BUTLER),
            new JinxInfo(Role.CANNIBAL, Role.JUGGLER),
            new JinxInfo(Role.CANNIBAL, Role.PRINCESS),
            new JinxInfo(Role.CANNIBAL, Role.ZEALOT),
            new JinxInfo(Role.CERENOVUS, Role.GOBLIN),
            new JinxInfo(Role.HERETIC, Role.BARON),
            new JinxInfo(Role.HERETIC, Role.GODFATHER),
            new JinxInfo(Role.HERETIC, Role.LLEECH),
            new JinxInfo(Role.HERETIC, Role.PIT_HAG),
            new JinxInfo(Role.HERETIC, Role.SPY),
            new JinxInfo(Role.HERETIC, Role.WIDOW),
            new JinxInfo(Role.LEGION, Role.ENGINEER),
            new JinxInfo(Role.LEGION, Role.HATTER),
            new JinxInfo(Role.LEGION, Role.MINSTREL),
            new JinxInfo(Role.LEGION, Role.POLITICIAN),
            new JinxInfo(Role.LEGION, Role.PREACHER),
            new JinxInfo(Role.LEGION, Role.SUMMONER),
            new JinxInfo(Role.LEGION, Role.ZEALOT),
            new JinxInfo(Role.LEVIATHAN, Role.BANSHEE),
            new JinxInfo(Role.LEVIATHAN, Role.EXORCIST),
            new JinxInfo(Role.LEVIATHAN, Role.FARMER),
            new JinxInfo(Role.LEVIATHAN, Role.GRANDMOTHER),
            new JinxInfo(Role.LEVIATHAN, Role.HATTER),
            new JinxInfo(Role.LEVIATHAN, Role.INNKEEPER),
            new JinxInfo(Role.LEVIATHAN, Role.KING),
            new JinxInfo(Role.LEVIATHAN, Role.MAYOR),
            new JinxInfo(Role.LEVIATHAN, Role.MONK),
            new JinxInfo(Role.LEVIATHAN, Role.PIT_HAG),
            new JinxInfo(Role.LEVIATHAN, Role.RAVENKEEPER),
            new JinxInfo(Role.LEVIATHAN, Role.SAGE),
            new JinxInfo(Role.LEVIATHAN, Role.SOLDIER),
            new JinxInfo(Role.LIL_MONSTA, Role.HATTER),
            new JinxInfo(Role.LIL_MONSTA, Role.MAGICIAN),
            new JinxInfo(Role.LIL_MONSTA, Role.POPPY_GROWER),
            new JinxInfo(Role.LIL_MONSTA, Role.PSYCHOPATH),
            new JinxInfo(Role.LIL_MONSTA, Role.SCARLET_WOMAN),
            new JinxInfo(Role.LIL_MONSTA, Role.VIZIER),
            new JinxInfo(Role.LLEECH, Role.MASTERMIND),
            new JinxInfo(Role.LLEECH, Role.SLAYER),
            new JinxInfo(Role.MAGICIAN, Role.LEGION),
            new JinxInfo(Role.MAGICIAN, Role.MARIONETTE),
            new JinxInfo(Role.MAGICIAN, Role.SPY),
            new JinxInfo(Role.MAGICIAN, Role.VIZIER),
            new JinxInfo(Role.MAGICIAN, Role.WIDOW),
            new JinxInfo(Role.MAGICIAN, Role.WRAITH),
            new JinxInfo(Role.MARIONETTE, Role.BALLOONIST),
            new JinxInfo(Role.MARIONETTE, Role.HUNTSMAN),
            new JinxInfo(Role.MARIONETTE, Role.KAZALI),
            new JinxInfo(Role.MARIONETTE, Role.LIL_MONSTA),
            new JinxInfo(Role.MARIONETTE, Role.SUMMONER),
            new JinxInfo(Role.MASTERMIND, Role.VIGORMORTIS),
            new JinxInfo(Role.MATHEMATICIAN, Role.CHAMBERMAID),
            new JinxInfo(Role.MATHEMATICIAN, Role.DRUNK),
            new JinxInfo(Role.MATHEMATICIAN, Role.LUNATIC),
            new JinxInfo(Role.MATHEMATICIAN, Role.MARIONETTE),
            new JinxInfo(Role.PIT_HAG, Role.CULT_LEADER),
            new JinxInfo(Role.PIT_HAG, Role.DAMSEL),
            new JinxInfo(Role.PIT_HAG, Role.GOON),
            new JinxInfo(Role.PIT_HAG, Role.OGRE),
            new JinxInfo(Role.PIT_HAG, Role.POLITICIAN),
            new JinxInfo(Role.PIT_HAG, Role.VILLAGE_IDIOT),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.BARON),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.BOOMDANDY),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.EVIL_TWIN),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.FEARMONGER),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.GOBLIN),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.MARIONETTE),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.SCARLET_WOMAN),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.SPY),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.WRAITH),
            new JinxInfo(Role.RECLUSE, Role.OGRE),
            new JinxInfo(Role.RECLUSE, Role.SAGE),
            new JinxInfo(Role.RIOT, Role.ATHEIST),
            new JinxInfo(Role.RIOT, Role.BANSHEE),
            new JinxInfo(Role.RIOT, Role.EXORCIST),
            new JinxInfo(Role.RIOT, Role.FARMER),
            new JinxInfo(Role.RIOT, Role.GRANDMOTHER),
            new JinxInfo(Role.RIOT, Role.INNKEEPER),
            new JinxInfo(Role.RIOT, Role.KING),
            new JinxInfo(Role.RIOT, Role.MAYOR),
            new JinxInfo(Role.RIOT, Role.MONK),
            new JinxInfo(Role.RIOT, Role.RAVENKEEPER),
            new JinxInfo(Role.RIOT, Role.SAGE),
            new JinxInfo(Role.RIOT, Role.SOLDIER),
            new JinxInfo(Role.SCARLET_WOMAN, Role.AL_HADIKHIA),
            new JinxInfo(Role.SCARLET_WOMAN, Role.FANG_GU),
            new JinxInfo(Role.SPY, Role.DAMSEL),
            new JinxInfo(Role.SPY, Role.OGRE),
            new JinxInfo(Role.SPY, Role.POPPY_GROWER),
            new JinxInfo(Role.SUMMONER, Role.CLOCKMAKER),
            new JinxInfo(Role.SUMMONER, Role.COURTIER),
            new JinxInfo(Role.SUMMONER, Role.ENGINEER),
            new JinxInfo(Role.SUMMONER, Role.HATTER),
            new JinxInfo(Role.SUMMONER, Role.KAZALI),
            new JinxInfo(Role.SUMMONER, Role.LORD_OF_TYPHON),
            new JinxInfo(Role.SUMMONER, Role.PIT_HAG),
            new JinxInfo(Role.SUMMONER, Role.POPPY_GROWER),
            new JinxInfo(Role.SUMMONER, Role.PREACHER),
            new JinxInfo(Role.SUMMONER, Role.PUKKA),
            new JinxInfo(Role.SUMMONER, Role.ZOMBUUL),
            new JinxInfo(Role.VIZIER, Role.ALSAAHIR),
            new JinxInfo(Role.VIZIER, Role.COURTIER),
            new JinxInfo(Role.VIZIER, Role.FEARMONGER),
            new JinxInfo(Role.VIZIER, Role.INVESTIGATOR),
            new JinxInfo(Role.VIZIER, Role.POLITICIAN),
            new JinxInfo(Role.VIZIER, Role.PREACHER),
            new JinxInfo(Role.VIZIER, Role.ZEALOT),
            new JinxInfo(Role.VORTOX, Role.BANSHEE),
            new JinxInfo(Role.WIDOW, Role.DAMSEL),
            new JinxInfo(Role.WIDOW, Role.POPPY_GROWER),
            new JinxInfo(Role.YAGGABABBLE, Role.EXORCIST)
    );
}