package com.autumnwind.botb.util;

import java.util.List;

public class Jinxes {

    public record JinxInfo(Role role1, Role role2, String description) {}

    public static final List<JinxInfo> JINX_LIST = List.of(
            new JinxInfo(Role.ALCHEMIST, Role.BOFFIN, "If the Alchemist has the Boffin ability, the Alchemist does not learn what ability the Demon has."),
            new JinxInfo(Role.ALCHEMIST, Role.MARIONETTE, "An Alchemist-Marionette has no Marionette ability & the Marionette is in play."),
            new JinxInfo(Role.ALCHEMIST, Role.MASTERMIND, "An Alchemist-Mastermind has no Mastermind ability & the Mastermind is not-in-play."),
            new JinxInfo(Role.ALCHEMIST, Role.ORGAN_GRINDER, "If the Alchemist has the Organ Grinder ability, the Organ Grinder is in play. If both are sober, both are drunk."),
            new JinxInfo(Role.ALCHEMIST, Role.SPY, "An Alchemist-Spy has no Spy ability & a Spy is in play. After each execution, a living Alchemist-Spy may publicly guess a living player as the Spy. If correct, the Demon must choose the Spy tonight."),
            new JinxInfo(Role.ALCHEMIST, Role.SUMMONER, "The Alchemist-Summoner does not get bluffs, and chooses which Demon but not which player. If they die before this happens, evil wins. [No Demon]"),
            new JinxInfo(Role.ALCHEMIST, Role.WIDOW, "An Alchemist-Widow has no Widow ability & a Widow is in play. After each execution, a living Alchemist-Widow may publicly guess a living player as the Widow. If correct, the Demon must choose the Widow tonight."),
            new JinxInfo(Role.ALCHEMIST, Role.WRAITH, "An Alchemist-Wraith has no Wraith ability & a Wraith is in play. After each execution, a living Alchemist-Wraith may publicly guess a living player as the Wraith. If correct, the Demon must choose the Wraith tonight."),
            new JinxInfo(Role.AL_HADIKHIA, Role.MASTERMIND, "If the Al-Hadikhia dies by execution, and the Mastermind is alive, the Al-Hadikhia chooses 3 good players tonight: if all 3 choose to live, evil wins. Otherwise, good wins."),
            new JinxInfo(Role.AL_HADIKHIA, Role.PRINCESS, "If the Princess nominated & executed a player on their 1st day, no one dies to the Al-Hadikhia tonight."),
            new JinxInfo(Role.BOFFIN, Role.CULT_LEADER, "If the Demon has the Cult Leader ability, they can’t turn good due to this ability."),
            new JinxInfo(Role.BOFFIN, Role.DRUNK, "The Demon cannot have the Drunk ability."),
            new JinxInfo(Role.BOFFIN, Role.GOON, "If the Demon has the Goon ability, they can’t turn good due to this ability."),
            new JinxInfo(Role.BOFFIN, Role.HERETIC, "The Demon cannot have the Heretic ability."),
            new JinxInfo(Role.BOFFIN, Role.OGRE, "The Demon cannot have the Ogre ability."),
            new JinxInfo(Role.BOFFIN, Role.POLITICIAN, "The Demon cannot have the Politician ability."),
            new JinxInfo(Role.BOFFIN, Role.VILLAGE_IDIOT, "If there is a spare token, the Boffin can give the Demon the Village Idiot ability."),
            new JinxInfo(Role.BOUNTY_HUNTER, Role.KAZALI, "If the Kazali turns the Bounty Hunter into a Minion, an evil Townsfolk is not created."),
            new JinxInfo(Role.BOUNTY_HUNTER, Role.PHILOSOPHER, "If the Philosopher gains the Bounty Hunter ability, a Townsfolk might turn evil."),
            new JinxInfo(Role.BUTLER, Role.ORGAN_GRINDER, "If the Organ Grinder is causing eyes closed voting, the Butler may raise their hand to vote but their vote is only counted if their master voted too."),
            new JinxInfo(Role.CANNIBAL, Role.BUTLER, "If the Cannibal gains the Butler ability, the Cannibal learns this."),
            new JinxInfo(Role.CANNIBAL, Role.JUGGLER, "If the Juggler guesses on their first day and dies by execution, tonight the living Cannibal learns how many guesses the Juggler got correct."),
            new JinxInfo(Role.CANNIBAL, Role.PRINCESS, "If the Cannibal nominated, executed, & killed the Princess today, the Demon doesn’t kill tonight."),
            new JinxInfo(Role.CANNIBAL, Role.ZEALOT, "If the Cannibal gains the Zealot ability, the Cannibal learns this."),
            new JinxInfo(Role.CERENOVUS, Role.GOBLIN, "The Cerenovus may choose to make a player mad that they are the Goblin."),
            new JinxInfo(Role.HERETIC, Role.BARON, "Only 1 jinxed character can be in play."),
            new JinxInfo(Role.HERETIC, Role.GODFATHER, "Only 1 jinxed character can be in play."),
            new JinxInfo(Role.HERETIC, Role.LLEECH, "Only 1 jinxed character can be in play."),
            new JinxInfo(Role.HERETIC, Role.PIT_HAG, "Only 1 jinxed character can be in play."),
            new JinxInfo(Role.HERETIC, Role.SPY, "Only 1 jinxed character can be in play."),
            new JinxInfo(Role.HERETIC, Role.WIDOW, "Only 1 jinxed character can be in play."),
            new JinxInfo(Role.LEGION, Role.ENGINEER, "If Legion is created, all evil players become Legion. If Legion is in play, the Engineer starts knowing this but has no ability."),
            new JinxInfo(Role.LEGION, Role.HATTER, "If Legion is created, all evil players become Legion. If Legion is in play, the Hatter has no ability."),
            new JinxInfo(Role.LEGION, Role.MINSTREL, "If Legion died by execution today, Legion keeps their ability, but the Minstrel might learn they are Legion."),
            new JinxInfo(Role.LEGION, Role.POLITICIAN, "The Politician might register as evil to Legion."),
            new JinxInfo(Role.LEGION, Role.PREACHER, "If the Preacher chooses Legion, Legion keeps their ability, but the Preacher might learn they are Legion."),
            new JinxInfo(Role.LEGION, Role.SUMMONER, "If Legion is summoned, all evil players become Legion. "),
            new JinxInfo(Role.LEGION, Role.ZEALOT, "The Zealot might register as evil to Legion."),
            new JinxInfo(Role.LEVIATHAN, Role.BANSHEE, "Each night*, the Leviathan chooses an alive good player (different to previous nights): a chosen Banshee dies & gains their ability."),
            new JinxInfo(Role.LEVIATHAN, Role.EXORCIST, "If the Leviathan nominates and executes the Exorcist-chosen player, good wins."),
            new JinxInfo(Role.LEVIATHAN, Role.FARMER, "Each night*, the Leviathan chooses an alive good player (different to previous nights): a chosen Farmer uses their ability but does not die."),
            new JinxInfo(Role.LEVIATHAN, Role.GRANDMOTHER, "If the Leviathan is in play and the Grandchild dies by execution, evil wins."),
            new JinxInfo(Role.LEVIATHAN, Role.HATTER, "The Leviathan cannot enter play after day 5."),
            new JinxInfo(Role.LEVIATHAN, Role.INNKEEPER, "If the Leviathan nominates and executes an Innkeeper-protected player, good wins."),
            new JinxInfo(Role.LEVIATHAN, Role.KING, "If the Leviathan is in play, and at least 1 player is dead, the King learns an alive character each night."),
            new JinxInfo(Role.LEVIATHAN, Role.MAYOR, "If the Leviathan and the Mayor are alive on day 5 & no execution occurs, good wins."),
            new JinxInfo(Role.LEVIATHAN, Role.MONK, "If the Leviathan nominates and executes the Monk-protected player, good wins."),
            new JinxInfo(Role.LEVIATHAN, Role.PIT_HAG, "The Leviathan cannot enter play after day 5."),
            new JinxInfo(Role.LEVIATHAN, Role.RAVENKEEPER, "Each night*, the Leviathan chooses an alive player (different to previous nights): a chosen Ravenkeeper uses their ability but does not die."),
            new JinxInfo(Role.LEVIATHAN, Role.SAGE, "Each night*, the Leviathan chooses an alive good player (different to previous nights): a chosen Sage uses their ability but does not die."),
            new JinxInfo(Role.LEVIATHAN, Role.SOLDIER, "If the Leviathan nominates and executes the Soldier, good wins."),
            new JinxInfo(Role.LIL_MONSTA, Role.HATTER, "If the Hatter dies & the Demon chooses Lil' Monsta, they also choose a Minion to become."),
            new JinxInfo(Role.LIL_MONSTA, Role.MAGICIAN, "If the Magician is alive, the Storyteller chooses which Minion babysits Lil' Monsta. "),
            new JinxInfo(Role.LIL_MONSTA, Role.POPPY_GROWER, "If Lil' Monsta & the Poppy Grower are alive, Minions wake one by one, until one of them chooses to take the Lil' Monsta token."),
            new JinxInfo(Role.LIL_MONSTA, Role.PSYCHOPATH, "If the Psychopath is babysitting Lil' Monsta, they die when executed."),
            new JinxInfo(Role.LIL_MONSTA, Role.SCARLET_WOMAN, "If Lil' Monsta dies with 5 or more players alive, the Scarlet Woman babysits Lil' Monsta for the rest of the game."),
            new JinxInfo(Role.LIL_MONSTA, Role.VIZIER, "If the Vizier is babysitting Lil' Monsta, they die when executed."),
            new JinxInfo(Role.LLEECH, Role.MASTERMIND, "If the Mastermind is alive and the Lleech host dies by execution, the Lleech lives but loses their ability."),
            new JinxInfo(Role.LLEECH, Role.SLAYER, "If the Slayer slays the Lleech host, the host dies."),
            new JinxInfo(Role.MAGICIAN, Role.LEGION, "The Magician wakes with Legion and might register as evil. Legion knows if a Magician is in play, but not which player it is."),
            new JinxInfo(Role.MAGICIAN, Role.MARIONETTE, "If the Magician is alive, the Demon doesn't know which neighbor is the Marionette."),
            new JinxInfo(Role.MAGICIAN, Role.SPY, "When the Spy sees the Grimoire, the Demon and Magician's character tokens are removed."),
            new JinxInfo(Role.MAGICIAN, Role.VIZIER, "If the Vizier is in play, the Magician has no ability but is immune to the Vizier's ability."),
            new JinxInfo(Role.MAGICIAN, Role.WIDOW, "When the Widow sees the Grimoire, the Demon and Magician's character tokens are removed."),
            new JinxInfo(Role.MAGICIAN, Role.WRAITH, "After each execution, the living Magician may publicly guess a living player as the Wraith. If correct, the Demon must choose the Wraith tonight."),
            new JinxInfo(Role.MARIONETTE, Role.BALLOONIST, "If the Marionette thinks that they are the Balloonist, an Outsider might have been added during setup."),
            new JinxInfo(Role.MARIONETTE, Role.HUNTSMAN, "If the Marionette thinks that they are the Huntsman, the Damsel was added during setup."),
            new JinxInfo(Role.MARIONETTE, Role.KAZALI, "If there would be a Marionette in play, they enter play after the Demon & must start as their neighbor."),
            new JinxInfo(Role.MARIONETTE, Role.LIL_MONSTA, "If there would be a Marionette in play, they enter play after the Demon & must start as their neighbor."),
            new JinxInfo(Role.MARIONETTE, Role.SUMMONER, "If there would be a Marionette in play, they enter play after the Demon & must start as their neighbor."),
            new JinxInfo(Role.MASTERMIND, Role.VIGORMORTIS, "A Mastermind that has their ability keeps it if the Vigormortis dies."),
            new JinxInfo(Role.MATHEMATICIAN, Role.CHAMBERMAID, "The Chambermaid can detect if the Mathematician will wake tonight."),
            new JinxInfo(Role.MATHEMATICIAN, Role.DRUNK, "The Mathematician might learn if the Drunk's ability yielded false info or failed to work properly."),
            new JinxInfo(Role.MATHEMATICIAN, Role.LUNATIC, "The Mathematician might learn if the Lunatic attacks a different player than the real Demon attacked."),
            new JinxInfo(Role.MATHEMATICIAN, Role.MARIONETTE, "The Mathematician might learn if the Marionette's ability yielded false info or failed to work properly."),
            new JinxInfo(Role.PIT_HAG, Role.CULT_LEADER, "If the Pit-Hag turns an evil player into the Cult Leader, they can't turn good due to their own ability."),
            new JinxInfo(Role.PIT_HAG, Role.DAMSEL, "If a Pit-Hag creates a Damsel, the Storyteller chooses which player it is."),
            new JinxInfo(Role.PIT_HAG, Role.GOON, "If the Pit-Hag turns an evil player into the Goon, they can't turn good due to their own ability."),
            new JinxInfo(Role.PIT_HAG, Role.OGRE, "If the Pit-Hag turns an evil player into the Ogre, they can't turn good due to their own ability."),
            new JinxInfo(Role.PIT_HAG, Role.POLITICIAN, "If the Pit-Hag turns an evil player into the Politician, they can't turn good due to their own ability."),
            new JinxInfo(Role.PIT_HAG, Role.VILLAGE_IDIOT, "If there is a spare token, the Pit-Hag can create an extra Village Idiot. If so, the drunk Village Idiot might change."),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.BARON, "If the Storyteller would gain the Baron ability, up to two players become Outsiders."),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.BOOMDANDY, "If the Storyteller would gain the Boomdandy ability, a player becomes the Boomdandy."),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.EVIL_TWIN, "If the Storyteller would gain the Evil Twin ability, a player becomes the Evil Twin."),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.FEARMONGER, "If the Storyteller would gain the Fearmonger ability, a Minion gains it, and learns this."),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.GOBLIN, "If the Storyteller would gain the Goblin ability, a Minion gains it, and learns this."),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.MARIONETTE, "If the Storyteller would gain the Marionette ability, one of the Demon's good neighbors becomes the Marionette."),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.SCARLET_WOMAN, "If the Storyteller would gain the Scarlet Woman ability, a Minion gains it, and learns this."),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.SPY, "If the Storyteller would gain the Spy ability, a Minion gains it, and learns this."),
            new JinxInfo(Role.PLAGUE_DOCTOR, Role.WRAITH, "If the Storyteller would gain the Wraith ability, a Minion gains it, and learns this."),
            new JinxInfo(Role.RECLUSE, Role.OGRE, "If the Recluse registers as evil to the Ogre, the Ogre learns that they are evil."),
            new JinxInfo(Role.RECLUSE, Role.SAGE, "The Recluse might register as the Demon to the Sage."),
            new JinxInfo(Role.RIOT, Role.ATHEIST, "During a riot, if the Storyteller is nominated, players vote. If they are \"about to die\", the game ends. If not, they nominate again."),
            new JinxInfo(Role.RIOT, Role.BANSHEE, "Each night*, Riot chooses an alive good player (different to previous nights): a chosen Banshee dies & gains their ability."),
            new JinxInfo(Role.RIOT, Role.EXORCIST, "If Riot nominates and executes the Exorcist-chosen player, good wins."),
            new JinxInfo(Role.RIOT, Role.FARMER, "Each night*, Riot chooses an alive good player (different to previous nights): a chosen Farmer uses their ability but does not die."),
            new JinxInfo(Role.RIOT, Role.GRANDMOTHER, "If Riot is in play and the Grandchild dies by execution, evil wins."),
            new JinxInfo(Role.RIOT, Role.INNKEEPER, "If Riot nominates and executes an Innkeeper-protected player, good wins."),
            new JinxInfo(Role.RIOT, Role.KING, "If Riot is in play, and at least 1 player is dead, the King learns an alive character each night."),
            new JinxInfo(Role.RIOT, Role.MAYOR, "The Mayor may choose to stop the riot. If they do so when only 1 Riot is alive, good wins. Otherwise, evil wins."),
            new JinxInfo(Role.RIOT, Role.MONK, "If Riot nominates and executes the Monk-protected player, good wins."),
            new JinxInfo(Role.RIOT, Role.RAVENKEEPER, "Each night*, Riot chooses an alive good player (different to previous nights): a chosen Ravenkeeper uses their ability but does not die."),
            new JinxInfo(Role.RIOT, Role.SAGE, "Each night*, Riot chooses an alive good player (different to previous nights): a chosen Sage uses their ability but does not die."),
            new JinxInfo(Role.RIOT, Role.SOLDIER, "If Riot nominates and executes the Soldier, good wins."),
            new JinxInfo(Role.SCARLET_WOMAN, Role.AL_HADIKHIA, "If there would be two Demons, one of which was the Scarlet Woman, the Scarlet Woman becomes the Scarlet Woman again."),
            new JinxInfo(Role.SCARLET_WOMAN, Role.FANG_GU, "If there would be two Demons, one of which was the Scarlet Woman, the Scarlet Woman remains the Scarlet Woman."),
            new JinxInfo(Role.SPY, Role.DAMSEL, "If the Spy is (or has been) in play, the Damsel is poisoned."),
            new JinxInfo(Role.SPY, Role.OGRE, "The Spy registers as evil to the Ogre."),
            new JinxInfo(Role.SPY, Role.POPPY_GROWER, "If the Poppy Grower has their ability, the Spy does not see the Grimoire."),
            new JinxInfo(Role.SUMMONER, Role.CLOCKMAKER, "The Summoner registers as the Demon to the Clockmaker."),
            new JinxInfo(Role.SUMMONER, Role.COURTIER, "If the living Summoner has no ability, the Storyteller has the Summoner ability."),
            new JinxInfo(Role.SUMMONER, Role.ENGINEER, "If the living Summoner is removed from play, the Storyteller has the Summoner ability."),
            new JinxInfo(Role.SUMMONER, Role.HATTER, "If the Summoner creates a second living Demon, deaths tonight are arbitrary."),
            new JinxInfo(Role.SUMMONER, Role.KAZALI, "If the Summoner creates a second living Demon, deaths tonight are arbitrary."),
            new JinxInfo(Role.SUMMONER, Role.LORD_OF_TYPHON, "If a Lord of Typhon is summoned, they must neighbor a Minion & their other neighbor becomes an evil Minion."),
            new JinxInfo(Role.SUMMONER, Role.PIT_HAG, "If the Summoner creates a second living Demon, deaths tonight are arbitrary."),
            new JinxInfo(Role.SUMMONER, Role.POPPY_GROWER, "If the Poppy Grower is alive on the 3rd night, the Summoner chooses which Demon but not which player."),
            new JinxInfo(Role.SUMMONER, Role.PREACHER, "If the living Summoner has no ability, the Storyteller has the Summoner ability."),
            new JinxInfo(Role.SUMMONER, Role.PUKKA, "The Summoner may summon a Pukka on the 2nd night instead of the 3rd."),
            new JinxInfo(Role.SUMMONER, Role.ZOMBUUL, "If the Summoner summons a dead player into the Zombuul, the Zombuul has already \"died once\"."),
            new JinxInfo(Role.VIZIER, Role.ALSAAHIR, "The Storyteller doesn't declare the Vizier is in play."),
            new JinxInfo(Role.VIZIER, Role.COURTIER, "If the Vizier loses their ability, they learn this, and cannot die during the day."),
            new JinxInfo(Role.VIZIER, Role.FEARMONGER, "The Vizier wakes with the Fearmonger, learns who they choose and cannot choose to immediately execute that player."),
            new JinxInfo(Role.VIZIER, Role.INVESTIGATOR, "The Storyteller doesn't declare the Vizier is in play."),
            new JinxInfo(Role.VIZIER, Role.POLITICIAN, "The Politician might register as evil to the Vizier."),
            new JinxInfo(Role.VIZIER, Role.PREACHER, "If the Vizier loses their ability, they learn this, and cannot die during the day."),
            new JinxInfo(Role.VIZIER, Role.ZEALOT, "The Zealot might register as evil to the Vizier."),
            new JinxInfo(Role.VORTOX, Role.BANSHEE, "If the Vortox kills the Banshee, all players learn that the Banshee has died."),
            new JinxInfo(Role.WIDOW, Role.DAMSEL, "If the Widow is (or has been) in play, the Damsel is poisoned."),
            new JinxInfo(Role.WIDOW, Role.POPPY_GROWER, "If the Poppy Grower has their ability, the Widow does not see the Grimoire."),
            new JinxInfo(Role.YAGGABABBLE, Role.EXORCIST, "If the Exorcist chooses the Yaggababble, the Yaggababble does not kill tonight.")
    );
}