package com.autumnwind.botb.util;

import com.autumnwind.botb.BloodOnTheBlocktower;
import java.util.Map;
import net.minecraft.locale.Language;

/** Almanac text per role. The text is in the lang file, only the icon artist is kept here. */
public class RoleDetails {

    public record RoleDetailData(Role role, String artist) {

        public String flavorText() {
            return text("flavor");
        }

        public String summary() {
            return text("summary");
        }

        public String examples() {
            return text("examples");
        }

        private String text(String part) {
            return Language.getInstance().getOrDefault("role." + BloodOnTheBlocktower.MOD_ID + "." + role.getId() + "." + part);
        }
    }

    private static final Map<Role, String> ARTISTS = Map.ofEntries(
            Map.entry(Role.CHEF, "The Yogscast"),
            Map.entry(Role.INVESTIGATOR, "The Yogscast"),
            Map.entry(Role.WASHERWOMAN, "The Yogscast"),
            Map.entry(Role.LIBRARIAN, "The Yogscast"),
            Map.entry(Role.EMPATH, "The Yogscast"),
            Map.entry(Role.FORTUNE_TELLER, "The Yogscast"),
            Map.entry(Role.UNDERTAKER, "The Yogscast"),
            Map.entry(Role.MONK, "The Yogscast"),
            Map.entry(Role.SLAYER, "The Yogscast"),
            Map.entry(Role.SOLDIER, "The Yogscast"),
            Map.entry(Role.RAVENKEEPER, "The Yogscast"),
            Map.entry(Role.VIRGIN, "The Yogscast"),
            Map.entry(Role.MAYOR, "The Yogscast"),
            Map.entry(Role.GRANDMOTHER, "The Yogscast"),
            Map.entry(Role.SAILOR, "The Yogscast"),
            Map.entry(Role.CHAMBERMAID, "The Yogscast"),
            Map.entry(Role.INNKEEPER, "The Yogscast"),
            Map.entry(Role.GAMBLER, "The Yogscast"),
            Map.entry(Role.EXORCIST, "The Yogscast"),
            Map.entry(Role.GOSSIP, "Autumn Wind"),
            Map.entry(Role.COURTIER, "The Yogscast"),
            Map.entry(Role.PROFESSOR, "The Yogscast"),
            Map.entry(Role.MINSTREL, "xerca0 (Music Maker Mod)"),
            Map.entry(Role.TEA_LADY, "The Yogscast"),
            Map.entry(Role.FOOL, "The Yogscast"),
            Map.entry(Role.PACIFIST, "The Yogscast"),
            Map.entry(Role.CLOCKMAKER, "The Yogscast"),
            Map.entry(Role.DREAMER, "The Yogscast"),
            Map.entry(Role.SNAKE_CHARMER, "The Yogscast"),
            Map.entry(Role.MATHEMATICIAN, "The Yogscast"),
            Map.entry(Role.FLOWERGIRL, "The Yogscast"),
            Map.entry(Role.TOWN_CRIER, "The Yogscast"),
            Map.entry(Role.ORACLE, "The Yogscast"),
            Map.entry(Role.SAVANT, "The Yogscast"),
            Map.entry(Role.SEAMSTRESS, "The Yogscast"),
            Map.entry(Role.PHILOSOPHER, "Autumn Wind"),
            Map.entry(Role.ARTIST, "The Yogscast"),
            Map.entry(Role.JUGGLER, "Autumn Wind"),
            Map.entry(Role.SAGE, "The Yogscast"),
            Map.entry(Role.NOBLE, "The Yogscast"),
            Map.entry(Role.PIXIE, "The Yogscast"),
            Map.entry(Role.GENERAL, "The Yogscast"),
            Map.entry(Role.KING, "The Yogscast"),
            Map.entry(Role.LYCANTHROPE, "The Yogscast"),
            Map.entry(Role.ENGINEER, "Unused Minecraft Gear + edits by Autumn Wind"),
            Map.entry(Role.HUNTSMAN, "The Yogscast"),
            Map.entry(Role.ALCHEMIST, "The Yogscast"),
            Map.entry(Role.CANNIBAL, "The Yogscast"),
            Map.entry(Role.AMNESIAC, "The Yogscast"),
            Map.entry(Role.FARMER, "The Yogscast"),
            Map.entry(Role.CHOIRBOY, "The Yogscast"),
            Map.entry(Role.MAGICIAN, "The Yogscast"),
            Map.entry(Role.POPPY_GROWER, "The Yogscast"),
            Map.entry(Role.ATHEIST, "The Yogscast"),
            Map.entry(Role.STEWARD, "The Yogscast"),
            Map.entry(Role.KNIGHT, "The Yogscast"),
            Map.entry(Role.SHUGENJA, "The Yogscast"),
            Map.entry(Role.BOUNTY_HUNTER, "The Yogscast"),
            Map.entry(Role.HIGH_PRIESTESS, "The Yogscast"),
            Map.entry(Role.BALLOONIST, "The Yogscast"),
            Map.entry(Role.PREACHER, "The Yogscast"),
            Map.entry(Role.VILLAGE_IDIOT, "The Yogscast"),
            Map.entry(Role.CULT_LEADER, "The Yogscast"),
            Map.entry(Role.ACROBAT, "The Yogscast"),
            Map.entry(Role.ALSAAHIR, "The Yogscast"),
            Map.entry(Role.NIGHTWATCHMAN, "The Yogscast"),
            Map.entry(Role.FISHERMAN, "The Yogscast"),
            Map.entry(Role.PRINCESS, "Autumn Wind"),
            Map.entry(Role.BANSHEE, "The Yogscast"),
            Map.entry(Role.BUTLER, "The Yogscast"),
            Map.entry(Role.SAINT, "The Yogscast"),
            Map.entry(Role.RECLUSE, "The Yogscast"),
            Map.entry(Role.DRUNK, "The Yogscast"),
            Map.entry(Role.GOON, "The Yogscast"),
            Map.entry(Role.LUNATIC, "The Yogscast"),
            Map.entry(Role.TINKER, "mezz (JEI)"),
            Map.entry(Role.MOONCHILD, "The Yogscast"),
            Map.entry(Role.MUTANT, "The Yogscast"),
            Map.entry(Role.BARBER, "Autumn Wind"),
            Map.entry(Role.SWEETHEART, "The Yogscast"),
            Map.entry(Role.KLUTZ, "The Yogscast"),
            Map.entry(Role.GOLEM, "The Yogscast"),
            Map.entry(Role.DAMSEL, "The Yogscast"),
            Map.entry(Role.SNITCH, "The Yogscast"),
            Map.entry(Role.HERETIC, "The Yogscast"),
            Map.entry(Role.PUZZLEMASTER, "Autumn Wind"),
            Map.entry(Role.HERMIT, "Autumn Wind"),
            Map.entry(Role.OGRE, "The Yogscast"),
            Map.entry(Role.PLAGUE_DOCTOR, "The Yogscast"),
            Map.entry(Role.HATTER, "The Yogscast"),
            Map.entry(Role.POLITICIAN, "The Yogscast"),
            Map.entry(Role.ZEALOT, "The Yogscast"),
            Map.entry(Role.POISONER, "The Yogscast"),
            Map.entry(Role.SPY, "The Yogscast"),
            Map.entry(Role.BARON, "The Yogscast"),
            Map.entry(Role.SCARLET_WOMAN, "The Yogscast"),
            Map.entry(Role.GODFATHER, "The Yogscast"),
            Map.entry(Role.DEVILS_ADVOCATE, "The Yogscast"),
            Map.entry(Role.ASSASSIN, "The Yogscast"),
            Map.entry(Role.MASTERMIND, "The Yogscast"),
            Map.entry(Role.WITCH, "The Yogscast"),
            Map.entry(Role.CERENOVUS, "The Yogscast"),
            Map.entry(Role.PIT_HAG, "The Yogscast"),
            Map.entry(Role.EVIL_TWIN, "The Betweenlands Team"),
            Map.entry(Role.MEZEPHELES, "fish0016054 (Fish's Undead Rising) + edits by Autumn Wind"),
            Map.entry(Role.FEARMONGER, "The Yogscast"),
            Map.entry(Role.PSYCHOPATH, "The Yogscast"),
            Map.entry(Role.MARIONETTE, "The Yogscast"),
            Map.entry(Role.BOOMDANDY, "The Yogscast"),
            Map.entry(Role.HARPY, "The Yogscast"),
            Map.entry(Role.WIZARD, "The Yogscast"),
            Map.entry(Role.WIDOW, "Me! (Mod Creator)"),
            Map.entry(Role.XAAN, "Autumn Wind"),
            Map.entry(Role.WRAITH, "imonk (itch.io) + edits by Autumn Wind"),
            Map.entry(Role.SUMMONER, "The Yogscast"),
            Map.entry(Role.GOBLIN, "The Yogscast"),
            Map.entry(Role.VIZIER, "The Yogscast"),
            Map.entry(Role.ORGAN_GRINDER, "starzz4every1 (Pinterest) + fez by Autumn Wind"),
            Map.entry(Role.BOFFIN, "The Yogscast"),
            Map.entry(Role.IMP, "The Yogscast"),
            Map.entry(Role.PUKKA, "The Yogscast"),
            Map.entry(Role.SHABALOTH, "The Yogscast"),
            Map.entry(Role.PO, "Autumn Wind"),
            Map.entry(Role.ZOMBUUL, "The Yogscast"),
            Map.entry(Role.FANG_GU, "The Yogscast"),
            Map.entry(Role.VIGORMORTIS, "The Yogscast"),
            Map.entry(Role.NO_DASHII, "The Yogscast"),
            Map.entry(Role.VORTOX, "The Yogscast"),
            Map.entry(Role.LEGION, "The Yogscast"),
            Map.entry(Role.LLEECH, "The Yogscast"),
            Map.entry(Role.AL_HADIKHIA, "The Yogscast"),
            Map.entry(Role.RIOT, "The Yogscast"),
            Map.entry(Role.LEVIATHAN, "The Yogscast"),
            Map.entry(Role.YAGGABABBLE, "The Yogscast"),
            Map.entry(Role.LIL_MONSTA, "The Yogscast"),
            Map.entry(Role.KAZALI, "The Yogscast"),
            Map.entry(Role.OJO, "The Yogscast"),
            Map.entry(Role.LORD_OF_TYPHON, "The Yogscast"),
            Map.entry(Role.THIEF, "TheCatghost"),
            Map.entry(Role.BUREAUCRAT, "Minecraft Magic Dungeons team"),
            Map.entry(Role.GUNSLINGER, "theregoestimmy (Revolver Bow Replacement dev)"),
            Map.entry(Role.SCAPEGOAT, "Autumn Wind"),
            Map.entry(Role.BEGGAR, "AppleRoar (Coins mod dev)"),
            Map.entry(Role.APPRENTICE, "tterrag1098 (Chisel mod dev)"),
            Map.entry(Role.MATRON, "Autumn Wind"),
            Map.entry(Role.JUDGE, "Autumn Wind"),
            Map.entry(Role.VOUDON, "Monumenta Team"),
            Map.entry(Role.BISHOP, "JoPe158"),
            Map.entry(Role.BARISTA, "TheWandererRaven (Raven Coffee dev)"),
            Map.entry(Role.HARLOT, "Autumn Wind"),
            Map.entry(Role.BUTCHER, "jmods (Butchery dev)"),
            Map.entry(Role.DEVIANT, "igalaxy (Collar Trinkets dev)"),
            Map.entry(Role.BONE_COLLECTOR, "Minecraft Bone item + edits by Autumn Wind"),
            Map.entry(Role.CACKLEJACK, "The Yogscast"),
            Map.entry(Role.GANGSTER, "sbom_xela (Alex's Mobs)"),
            Map.entry(Role.GNOME, "Terramity Team"),
            Map.entry(Role.ANGEL, "Autumn Wind"),
            Map.entry(Role.BUDDHIST, "Autumn Wind"),
            Map.entry(Role.DEUS_EX_FIASCO, "(stock image)"),
            Map.entry(Role.DJINN, "Tejty (Genie Lamp mod)"),
            Map.entry(Role.DOOMSAYER, "Autumn Wind"),
            Map.entry(Role.DUCHESS, "The Yogscast"),
            Map.entry(Role.FERRYMAN, "Autumn Wind"),
            Map.entry(Role.FIBBIN, "Autumn Wind"),
            Map.entry(Role.FIDDLER, "xerca0 (Music Maker Mod)"),
            Map.entry(Role.HELLS_LIBRARIAN, "The Yogscast"),
            Map.entry(Role.REVOLUTIONARY, "Autumn Wind"),
            Map.entry(Role.SENTINEL, "The Yogscast"),
            Map.entry(Role.SPIRIT_OF_IVORY, "Autumn Wind"),
            Map.entry(Role.TOYMAKER, "The Yogscast"),
            Map.entry(Role.BIG_WIG, "The Yogscast"),
            Map.entry(Role.BOOTLEGGER, "The Yogscast"),
            Map.entry(Role.GARDENER, "(stock image)"),
            Map.entry(Role.GOD_OF_UG, "The Yogscast"),
            Map.entry(Role.HINDU, "Autumn Wind"),
            Map.entry(Role.KNAVES, "The Yogscast"),
            Map.entry(Role.POPE, "u/Cosix101"),
            Map.entry(Role.STORM_CATCHER, "Autumn Wind"),
            Map.entry(Role.TOR, "Autumn Wind"),
            Map.entry(Role.VENTRILOQUIST, "Autumn Wind"),
            Map.entry(Role.ZENOMANCER, "Autumn Wind")
    );

    public static RoleDetailData get(Role role) {
        return new RoleDetailData(role, ARTISTS.getOrDefault(role, "Unknown"));
    }
}
